### PR TITLE
Adding GitHub Settings designs

### PR DESCRIPTION
**Pull request by dongniwang**
Adding designs for GitHub set up during first time user experience and GitHub Settings tab on Global Settings page. 

I do have a couple questions: 
- How do users get into the Syndesis environment?
  - If users have no OpenShift account, they need to create an OS account, then get to Syndesis Get Started Page 
  - If users have OpenShift account, after signing in OS account, can they go to Syndesis Get Started page right away? 

Reference: 
#29

### CODE REVIEW

**Comment by rhuss** [comment]
> If users have no OpenShift account, they need to create an OS account, then get to Syndesis Get Started Page

For TP1 this is not an automated process. You first sign up for a test Syndesis account (with your redhat account which you have created elsewhere). Then someone from Red Hat approves this request manually, the OpenShift account is created and the Syndesis installation has been performed in his account. Finally the use gets a mail where to login in Syndesis. At that point the OpenShift account is already created.

> If users have OpenShift account, after signing in OS account, can they go to Syndesis Get Started page right away?

Yes thats the idea when they follow the Syndesis link in the acceptance mail. However, they still can access the OpenShift console via another link but this is probably not something we announce.

**Comment by dongniwang** [comment]
I do have another question, this is probably related to how we want to implement it and whether or not we can do this right now:
Let say user selected an account in step 3, how do we know when to display the Success Message? How do we know for sure user is done with making a selection?

**Comment by rhuss** [comment]
actually, I think there should be a "Done" / "Ready" ... button at the bottom which is enabled if all required information has been collected.

**Comment by dongniwang** [comment]
@rhuss 

> actually, I think there should be a "Done" / "Ready" ... button at the bottom which is enabled if all required information has been collected.

I see where you're coming from. But adding a "Done" button essentially require users to perform two actions before actually getting to the Welcome Landing page.

**Comment by rhuss** [comment]
Ok, I see you point. I discussed with  @kahboom about this step, let me paste the IRC log here first:

```
ryordan
ro14nd, I see here https://goo.gl/d3iNZZ you mention that for step 3, configuring the integration location can be the user account or an organization- which is the ideal situation? i'm assuming organization, but the designs reflect a user account. perhaps this is related to the fact that we can't create an app programmatically so by default it will be a user account?  https://goo.gl/c2W6bF

ro14nd
ryordan: currently we do all GitHub operations with the user account itself. We would need to add support for an organisation still, both for retrieving the organisations for a user from github and for using that organisation when performeing GitHub actions like creating a repo.
so the idea is to have the user as default, also because he can have multiple orgas belonging to
I wonder whether this could be either presented in a single combo box (with the user as 1st entry, separator, then organizations), or 2 radio buttons, combined with a combobox for the orgas.

ryordan
i'm not sure i'm imagining it correctly lol, i would need an example. but radio buttons would imply that only the user account OR one/multiple organizations would be selectable? as i'd imagine you don't mean radio buttons for deciding on one organization.

ro14nd
its exactly this. either a user or one organization can be selected.

ryordan
ah I see
F
@freenode_igarashitm:matrix.org left the room.

ro14nd
its just the place where a repository for an integration will be created.

ryordan
if it's a user then multiple orgs can be selected, is that correct?

ro14nd
no, then no org can be selected.

ryordan
i don't know why i have that idea, i think i made it up
lol yes, okay that makes sense. thanks

ro14nd
you need a single place where to create the repositories: either at the user's account or below one organisation to which a user has write access.
Of course this could be also an option when creating an integration so integrations can be created at different places.
but for now its one for all integrations.
F
@freenode_jcordes:matrix.org left the room.

ryordan
right okay, thank you ro14nd. then the radio buttons do make sense. perhaps a radio button with a dropdown (i think that we both mean the same thing when we say combobox and dropdown), or small tabs with a dropdown.. maybe in the style of something like select2 that allows you to type/autocomplete

ro14nd
yeah, 2x radio buttons, "( ) user account" and "( )  [ ... orgas as dropdown ... ]" but actually would chose what fits the ux best. btw, I don't expect many orgas (max 10 maybe), and also there can be no organisations at all in which case we don't even need this step (because we then have to use the user account)
```

So actually this is a bit of a complex interaction which does not have a clear automatic end. Maybe a "select" button here to indicate when either the user or organisation has been selected.

**Comment by dongniwang** [comment]
Just added two screens before the success message. 

One screen with a "Complete Setup" button and then a loading screen. Would this help?

**Comment by dongniwang** [comment]
@rhuss just saw your comment on the account/organization, does it mean the current design is not clear enough that it's a single select? 

Do we want two radio buttons for this? 

cc: @kahboom

**Comment by rhuss** [comment]
@dongniwang Yes, it is a bit more complicated than only selecting a user account with a simple dropdown. I could imagine providing a single dropdown nevertheless which contains as the first line the user account and in the following lines the organizations that the user has access to. I think this is the least intrusive way to select a **single** user or organization. Maybe one can separate user and his organizations with a separator within the dropdown. 

Radio buttons might be overkill here.

**Comment by dongniwang** [comment]
@rhuss ok, thanks for the feedback! I just updated the design - added a separator line in step 3 dropdown. Hope this helps differentiate individual users from organizations. 

Here's the patternfly dropdown: http://www.patternfly.org/pattern-library/widgets/#dropdowns
image

**Comment by dongniwang** [comment]
Just checking to see if we need to make any more updates to the design. If not, can we merge this?

@rhuss @jimmidyson @kahboom @gashcrumb 
cc: @sjcox-rh

**Comment by rhuss** [comment]
@dongniwang the overall flow looks good to me !

There is one thing which puzzles me a bit: In order to get to the account and the organizations in step 3, the user needs to authenticate with GitHub, i.e. with an OAuth flow which requires the GitHub client id / secret just entered. This OAuth action needs to happen between step 2 and 3.

Since the implementation of this flow is quite involved (e.g. we don't have yet a custom GitHub OAuth flow (this is normally done by keycloak)), I wonder whether we should provide the selection of the GitHub location for creating integrations at this place at all. We could always default to the user account and allow changing to an organization in the global settings page. This would be much simpler and faster to implement.

@kcbabo @jimmidyson @kahboom @gashcrumb : Any thoughts on this ?

**Comment by kcbabo** [comment]
@rhuss If your suggestion gets us there faster, then it works for me.  We can always update later based on feedback.

**Comment by dongniwang** [comment]
> We could always default to the user account and allow changing to an organization in the global settings page. This would be much simpler and faster to implement.

I can update the design to reflect this. Thanks! @rhuss

**Comment by kahboom** [comment]
I agree with @rhuss on defaulting to the user account. I think it looks good to merge @dongniwang. 👍

**Comment by dongniwang** [comment]
Just updated step2 of the GitHub setup flow to include a trigger to GitHub OAuth flow once users have filled in the client ID and client secret. 

@kahboom @gashcrumb

**Pull request merged**
