### PR TITLE
Salesforce Dynamic Objects

### PR DESCRIPTION
**Pull request by sjcox-rh**
Design updates to the Salesforce Dynamic Objects.  Sorry this is posted again, accidentally merged the PR, oops!

### CODE REVIEW

**Comment by gashcrumb** [comment]
That green button is just too enticing...  :-) Maybe we should set up this repo to only allow merges with an approval from somenoe else by default?

**Comment by dongniwang** [comment]
> That green button is just too enticing... :-) Maybe we should set up this repo to only allow merges with an approval from somenoe else by default?

Is there a way to revert the merge action? Where did the merged one go...

**Comment by gashcrumb** [comment]
@dongniwang yeah, after a PR has been merged there's a `revert` button available which creates a new PR that reverts it.

**Comment by gashcrumb** [comment]
Oh, and the merged PR winds up on the master branch if you look at the history here -> https://github.com/syndesisio/syndesis-ux/commits/master

**Comment by rhuss** [comment]
@dongniwang @sjcox-rh The merge went to its final destination on the `master` branch, so the files are already in place. 

But that's no problem at all. When this PR gets eventually merged, it will override the files from the previous' PR merge. Updating a given design uses the same procedure (creating a PR for overwriting an existing document)

**Comment by sjcox-rh** [comment]
Ahh, thanks for the clarifying @rhuss and @gashcrumb. One day I'll get the hang of all of this!

**Comment by sjcox-rh** [comment]
@rhuss @gashcrumb @dongniwang Is this design good to go? Haven't recieved any feedback on it so wondering if it's good to merge (again).  Since I accidentally merged it, you can view the designs here:

https://github.com/syndesisio/syndesis-ux/blob/master/designs/salesforceobjects/salesforceobjects.md

If I need to make any changes, I'll update this PR :]

**Pull request merged**
