### PR TITLE
Repositioned breadcrumb in create integration flow

### PR DESCRIPTION
**Pull request by dongniwang**
Breadcrumb is now placed right below masthead to ensure better visual hierarchy.

### CODE REVIEW

**Comment by dongniwang** [comment]
@amysueg @sjcox-rh @kahboom @gashcrumb Please review.

**Comment by dongniwang** [comment]
@rhuss hmm, I see where you're coming from. What do others think about duplicating the buttons so they appear right below the form area? 

> You can enter the integration name on the left side column, but not the description.
When you press "Save as Draft" or "Publish" then this extra form appears only when the name is not set previously. Otherwise the final form is skipped. So there is no chance to edit the description in this case.

The integration name is a required field but the description is not. So as long as users have the integration name entered, they can "save as draft" or "publish". 

> When being on the 'Integration Details' page, there you can add the description inline. But when you then press "Edit Integration" you are not able to change the description there (only the name in the inline input field over the steps can be changed).

Yes, so we don't display the Name and Description page again given that we have an integration details page.

**Comment by rhuss** [comment]
> The integration name is a required field but the description is not. So as long as users have the integration name entered, they can "save as draft" or "publish".

My point is, that if you go this route (enter integration name in the text field above the flow graph) you **never** can enter a description on this "Edit Integration" page. You then only can enter a description on the "Integration Details" page with an inline text input. This feels inconsistent to me, because if you don't enter the name in the text input field and press then "Save" or "Publish" you _can_ enter a description (along with the required name). For consistency's sake, one should leave out the description here, too. But then it's still confusing that this can be entered only on the "Integration Details" pages which I mainly classify as a 'read-only' page.

This might sound a bit nit-picky but imagine that it's very likely that we will have additional optional values in addition to the description, like tags, notes, ... which will suffer to be not editable if not going the second route (via the final form).

**Comment by dongniwang** [comment]
I think the integration editor is a way to visually edit the integration. And the integration details page is a place to edit integration related properties. Does this make sense?

**Comment by rhuss** [comment]
Ok. So maybe then just omit the description on the 'Edit Integration' page altogether? This would be at least consistent (and I would be happy ;-). But as said, its just a detail, so can be decided still later, too. Let's move on ... ;-)

**Pull request merged**
