### PR TITLE
Technical Extension Design

### PR DESCRIPTION
**Pull request by dongniwang**
Designs for Technical Extension. 

Epic: https://github.com/syndesisio/syndesis-project/issues/125
UX issue: https://github.com/syndesisio/syndesis-ux/issues/44
User Story: https://github.com/syndesisio/syndesis-project/issues/152

Please note this is not the final design. Will work with @lburgazzoli to finalize everything. 

A few questions:
- Can user edit/make changes to Name and Description of the tech extension during the import process? 
   - If yes, is there a limitation for how long the description can be? 
- Is there a file size limitation for the upload?

### CODE REVIEW

**Comment by dongniwang** [comment]
@lburgazzoli @nicolaferraro @rhuss @kcbabo @gashcrumb @amysueg @sjcox-rh 

Please review!

**Comment by lburgazzoli** [comment]
I'm unsure about the possibility for the user to update name and description of an extension as they are likely to be overwritten by updates. Different user may then change the name after the extension is uploaded so it may be safer to keep such info read only and have the user ask the developer to update name/description if required.

Then I think it may be nice to see if and where an extension is used so one can know the impact of an update/delete, like:

- the tech extension detail page may also list the integration names using the extension
- the tech extension list may have ad additional column showing how many integrations are using a given extension
- the tech extension delete modal window should report a warning only if an extension is in use and in such case have an option to go to the details page (or something similar that shows the details)

**Comment by nicolaferraro** [comment]
Nice work!

My comments below:
- Agree with Luca to keep name/description read only if it's not a requirement to allow users to change them.
- Agree also that the list of integrations using the extension can be nice to have
- I'm ok with displaying errors right after file upload rather than in the detail page (as I suggested in another thread). Btw, this means we'll not show any detail about the extension in case some metadata field is erroneous or if the extension cannot be imported for other technical constraints.
- I think the "update" action (after upload) should have a warning similar to the one of the delete action, stating e.g. that integration using the extension (if any) should be updated manually (we can encode this on UI or better let the back-end generate "warnings" like those, so just display a list of warnings on the update page)
- Given the complexity of the topic, I'd add a warning dialog also on the "Import" action after upload (we can signal bad practices or ... version mismatch, after analysis of the extension binary)

**Comment by dongniwang** [comment]
Thanks for the feedback! @lburgazzoli @nicolaferraro My questions and comments below:

> the tech extension delete modal window should report a warning only if an extension is in use and in such case have an option to go to the details page (or something similar that shows the details)

We can certainly show the extension is in use and probably also include information such as in use by which integrations. I'm not sure which "details page" you're referring to here? 

The delete a tech extension can happen in two places: 1) Tech extension list page; 2) Tech extension details page. Are you suggesting we include an option to go to a tech extension details page or an integration details page? Since the warning message is a modal dialogue, I don't think having many links in a modal dialogue is a good idea. 

> I'm ok with displaying errors right after file upload rather than in the detail page (as I suggested in another thread). Btw, this means we'll not show any detail about the extension in case some metadata field is erroneous or if the extension cannot be imported for other technical constraints.

Yes. So uploading a tech extension file trigger two types of validation:
- Validate if the file type is correct. Right now, my understanding is that we only accept .jar file. 
- Validate if the file contains sufficient metadata for syndesis to extract information. 
Only when a file with correct file type and sufficient metadata would be processed. 

> I think the "update" action (after upload) should have a warning similar to the one of the delete action, stating e.g. that integration using the extension (if any) should be updated manually (we can encode this on UI or better let the back-end generate "warnings" like those, so just display a list of warnings on the update page)
Given the complexity of the topic, I'd add a warning dialog also on the "Import" action after upload (we can signal bad practices or ... version mismatch, after analysis of the extension binary)

You're right. We should have validation for the update action. In addition to file type and sufficient metedata, what else needs to be included? 

Also, it's important to give users clear instruction on how to "manually" update the integrations.

**Comment by lburgazzoli** [comment]
@dongniwang 

about the "details page" I was thinking to go to the "tech extension details page", not sure if is a good thing as UX prospective but the goal for me is to inform the user about the impacts, maybe the impacted integration could be listed on the delete modal window but I do not know what is the best user experience.

**Comment by dongniwang** [comment]
@lburgazzoli 

Sounds good! 

So if the user is trying to delete the tech extension from the list view, we can include the link to the details page in the modal window. But if the user is trying to delete the tech extension from the details page, they can just close the window and get to the details page.

**Comment by dongniwang** [comment]
@lburgazzoli @nicolaferraro 

Can you please let me know:
- Is there a file size limitation for the upload?
- Is .jar file the only acceptable format? Anything else?

**Comment by lburgazzoli** [comment]
@dongniwang 

- no file size limitation
- yes jar is the only acceptable format

**Comment by nicolaferraro** [comment]
@dongniwang we need to discuss more about additional checks that must be performed on the uploaded extension. From a backend pov I'm thinking to add a pluggable way to add a series of validation steps that turn into warnings. This way we may add more validations as we make progress with the tech extensions and we find issues.

Possible examples of warnings are:
- The uploaded extension requires incompatible versions of libraries x y and z. Versions will be overridden with the one supported by the runtime engine
- The extension requires module g-a-v that has known compatibility issues with the runtime engine
- Actions/parameters declared in the uploaded extensions do not match actions of the extension that is being replaced (in case of upgrade)

These are just examples, and we may discover more possible mistakes in the future. That's why I'd opt for a plain list of warnings provided by the backend, so it will be extensible.

**Comment by dongniwang** [comment]
Thanks @lburgazzoli ! @TovaCohen FYI - .jar is the only acceptable format. 

@nicolaferraro thanks for the detailed feedback! From a UX/UI point of view, the look and feel of the error/warning messages is the same expect for the content. 

Tagging the font-end folks here so they know about the validation part: @gashcrumb @kahboom @seanforyou23

**Comment by dongniwang** [comment]
@lburgazzoli @nicolaferraro Updated the design to reflect what we discussed. 

Changes include:
- Read only for name and description when importing. 
- Added a column in list view to show how many integrations are using a given tech extension. Also added this info on the tech extension details page. 
- Show related integration info in delete warning message. 

FYI - @TovaCohen I included text changes in the designs as well. 

If things are in pretty good shape, can we please merge this PR so the front end folks can start working on this? 

Thanks all!

**Comment by kcbabo** [comment]
@lburgazzoli : we should document (and potentially enforce) that extensions align to a BOM specifically created for GAV alignment of extensions.  That should eliminate the case where incompatible versions of libraries are included, although people could still try and override local to their extension project, so still good to have the check.

**Comment by lburgazzoli** [comment]
@kcbabo we'll provide an archetype or project template that includes camel/syndesis/springboot BOMs and the maven plugin that packages the extension does also an initial filtering of dependencies based on group/artifact so for most of the case we should be safe although some edge case are still possible so the validation step may catch them. Not sure if we can cover everything possible case but we try :)

**Comment by lburgazzoli** [comment]
@dongniwang lgtm
@nicolaferraro any additional comment ?

**Comment by nicolaferraro** [comment]
@dongniwang lgtm!

**Pull request merged**
