### PR TITLE
High fidelity design of global settings page

### PR DESCRIPTION
**Pull request by dongniwang**
This is the first try of the high fidelity design of the global settings page.

### CODE REVIEW

**Comment by dongniwang** [comment]
@syndesisio/design-ux please review and provide feedback! Thank you!

**Comment by gashcrumb** [comment]
I wasn't sure which issue would be the best to link this PR too, so I linked it to a bunch :-)

**Comment by gashcrumb** [comment]
Looks good to me, I was wondering if adding an OAuth endpoint via the UI is necessary or not, but I see no reason not to support it as eventually users will definitely have their own stuff they'll want to integrate with.

**Comment by rhuss** [comment]
@gashcrumb @dongniwang sorry for the confusion about the linking confusion wrt to which image this PR should be linked.

The idea is:

* Every PR has a corresponding task to which it is linked. This task lives in the same repository as the PR. In this case, it is #6. Both PR and issue are nicely presented together in the ZenHub board.
* The task is then linked to a top-level "Epic". So here #6 is linked to https://github.com/syndesisio/syndesis-project/issues/13 ("Epics" live in syndesis-project)
* All other tasks for this story are linked to this epic. 

So the rule of thumb is:

* The PR links to an issue in the same repo.
* Each such issue is linked to an epic in syndesis-project.

You are free to cross link dependencies across repos (e.g. when a task in syndesis-ui depends on this syndesis-ux PR.

I'm going to update the links accordingly if you don't mind.

**Comment by rhuss** [comment]
Also I would like to use dependencies only among issues, if possible (not an issue depends on an PR, this seems to be already clear becuase both are linked together).

**Comment by rhuss** [comment]
@dongniwang I probably would avoid spaces in filenames, as this is difficult to use in Markdown links. You would have to use '+' instead of ' ' when referring them from a markdown link.

But best to avoid space as it also needs to escaped on the command line, too.

**Comment by dongniwang** [comment]
@rhuss I was wondering why the md file is not rendering the img. Thanks for letting me know!

**Comment by dongniwang** [comment]
> On page 5 for adding a new oauth client should we allow the user to provide a custom icon? Also is there a default icon we'd use if no icon is set for the oauth client?

@gashcrumb: Good point! The page is actually new which means it was not in the original wireframes, I actually don't know what are the common values for this form. But I can add the icon field for sure.

**Comment by TovaCohen** [comment]
It seems to me that an integrator is not registering Twitter or registering Salesforce, rather the integrator registers Syndesis in or with Twitter, registers Syndesis in or with Salesforce, and so on. So the explanation

     Register applications to allow Syndesis to access information and act on your behalf.

Is misleading. I expected something like this:

     Register Syndesis with the applications you want to connect to in an integration.

Also, I did not expect to see anything about Syndesis acting on your behalf on this page. This is registration.
Isn't it the authorization part that involves a particular user account?
 
Also, having "OAuth" in the title seems too geeky. Could the tab and also the title be:

    Registrations

**Comment by dongniwang** [comment]
@TovaCohen Thanks for the feedback! I can certainly change the text to what you suggested. I do feel that OAuth needs to be in the title since Registration to me is pretty vague.

**Comment by chirino** [comment]
I don't think users will be able to add new oauth applications.  The oauth applications which can be configured is based on connectors that are known to the system and thats currently static.

**Comment by chirino** [comment]
What does the register button do?  Does it just show the form?

**Comment by dongniwang** [comment]
> I don't think users will be able to add new oauth applications. The oauth applications which can be configured is based on connectors that are known to the system and thats currently static.

@chirino you mean the "Add New" button, right? I probably misunderstood the user story. It's easy to take that out. Then my question is, what do users need to do or what can users do on this page? Is it just configured (register/delete/update) client id and client secret? 

> What does the register button do? Does it just show the form?
Yes, it just expand the form. Does it make you feel like it's going to take users to another page or window?

**Comment by dongniwang** [comment]
Just updated the text in the design and removed the **Add New** function. 

Any other changes I missed?

**Pull request merged**
